main = "src/index.ts"
compatibility_date = "2023-04-16"
minify = false

name = "firstplace-dev"
vars = { ENVIRONMENT = "development", BASE_URL = "https://firstplace-dev.5r.workers.dev" }

[env.staging]
name = "firstplace-staging"
vars = { ENVIRONMENT = "staging", BASE_URL = "https://firstplace-staging.5r.workers.dev"}

[env.production]
name = "firstplace"
vars = { ENVIRONMENT = "production", BASE_URL = "https://firstplace.5r.workers.dev" }
