name: Deploy App (Staging)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: staging
    runs-on: ubuntu-latest
    env:
      MIGRATIONS_SCRIPT_PATH: 'migrations/migrate.ts'
      INIT_APP_ENDPOINT: 'https://leaderboards-staging.5r.workers.dev/update'
    steps:
      - uses: actions/checkout@v2

      - run: npm install

      - name: Compile TypeScript
        run: npx tsc --build tsconfig.json

      - name: Run migrations
        env: 
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
        run: npx tsx ${{ env.MIGRATIONS_SCRIPT_PATH }}

      - name: Publish to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: staging
          secrets: |
            DISCORD_TOKEN
            APPLICATION_ID
            PUBLIC_KEY
            CLIENT_SECRET
            SENTRY_DSN
            APP_KEY
            POSTGRES_URL
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          APP_KEY: ${{ secrets.APP_KEY }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}

      - name: Wait for deployment
        run: sleep 3

      - name: Initialize app
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ env.INIT_APP_ENDPOINT }}
          method: POST
          customHeaders: '{"Authorization":"${{ secrets.APP_KEY }}"}'
