name: Deploy App (Staging)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: staging
    runs-on: ubuntu-latest
    env:
      MIGRATIONS_SCRIPT_PATH: 'migrations/migrate.ts'
      INIT_APP_ENDPOINT: 'https://firstplace-staging.5r.workers.dev/init'
    steps:
      - uses: actions/checkout@v2

      - run: npm install

      - name: Compile TypeScript
        run: npx tsc --build tsconfig.json

      - name: Run migrations
        env: 
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
        run: npx tsx $MIGRATIONS_SCRIPT_PATH

      - name: Publish to Cloudflare Workers
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: staging

      - name: Wait 5 seconds
        run: sleep 5

      - name: Initialize app
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ env.INIT_APP_ENDPOINT }}
          method: POST
          customHeaders: '{"Authorization":"${{ secrets.APP_KEY }}"}'
